// blueprint title (template title)
title: default

// page settings
options:
  delete: true
  preview: true
  status: true
  url: false
  template: false

// subpages settings
pages: false

// file settings
files: false

// fields with their fields types and options
fields:
  title:
    label: Nome del sito
    type: text
  second_title:
    label: Titolo del sito
    type: textarea
  subtitle:
    label: Sottotitolo
    type: textarea